### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sushi1129** [sushi1129/protospace-36374#1]
# URL
https://protospace-36374.herokuapp.com/

**Comment by snkw-works** [comment]
@sushi1129 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
ユーザー名が一部正しく表示されていない状態です。
<img width="1440" alt="スクリーンショット_2021-08-23_15_49_27" src="https://user-images.githubusercontent.com/54050089/130403231-d32d57f0-2cd4-4471-9433-a8631ff46505.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takumi0530** [comment]
@sushi1129 さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
